// Adapta datos entre formulario de variante y payload para la API externa.
// No se envía codigoProducto porque la base lo genera automáticamente.

export const initialVariantFormData = {
  producto_id: '',
  codigo_referencia: '',
  nombre_variante: '',
  medida_largo: '',
  medida_ancho: '',
  medida_alto: '',
  unidad_medida: 'cm',
  etiqueta_medida: '',
  color_principal: '',
  material_variante: '',
  acabado: '',
  peso_gramos: '',
  precio: '',
  precio_comparacion: '',
  costo: '',
  stock_minimo: 5,
  es_predeterminada: false,
  es_activa: true,
};

export const variantToFormData = (variant = {}) => ({
  producto_id: variant.producto_id || '',
  codigo_referencia: variant.codigo_referencia || '',
  nombre_variante: variant.nombre_variante || '',
  medida_largo: variant.medida_largo ?? '',
  medida_ancho: variant.medida_ancho ?? '',
  medida_alto: variant.medida_alto ?? '',
  unidad_medida: variant.unidad_medida || 'cm',
  etiqueta_medida: variant.etiqueta_medida || '',
  color_principal: variant.color_principal || '',
  material_variante: variant.material_variante || '',
  acabado: variant.acabado || '',
  peso_gramos: variant.peso_gramos ?? '',
  precio: variant.precio ?? '',
  precio_comparacion: variant.precio_comparacion ?? '',
  costo: variant.costo ?? '',
  stock_minimo: variant.stock_minimo ?? 5,
  es_predeterminada: Boolean(variant.es_predeterminada),
  es_activa: Boolean(variant.es_activa),
});

export const formDataToVariantPayload = (formData) => ({
  producto_id: formData.producto_id,
  codigo_referencia: formData.codigo_referencia.trim() || null,
  nombre_variante: formData.nombre_variante.trim() || null,
  medida_largo: formData.medida_largo ? Number(formData.medida_largo) : null,
  medida_ancho: formData.medida_ancho ? Number(formData.medida_ancho) : null,
  medida_alto: formData.medida_alto ? Number(formData.medida_alto) : null,
  unidad_medida: formData.unidad_medida || 'cm',
  etiqueta_medida: formData.etiqueta_medida.trim() || null,
  color_principal: formData.color_principal.trim() || null,
  material_variante: formData.material_variante.trim() || null,
  acabado: formData.acabado.trim() || null,
  peso_gramos: formData.peso_gramos ? Number(formData.peso_gramos) : null,
  precio: Number(formData.precio || 0),
  precio_comparacion: formData.precio_comparacion ? Number(formData.precio_comparacion) : null,
  costo: formData.costo ? Number(formData.costo) : null,
  stock_minimo: Number(formData.stock_minimo || 5),
  es_predeterminada: formData.es_predeterminada,
  es_activa: formData.es_activa,
});
